# Generated by Django 4.2.9 on 2024-03-19 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="укажите дату рождения",
                        null=True,
                        verbose_name="дата рождения",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="загрузите автарку",
                        null=True,
                        upload_to=users.models.get_path_image,
                        verbose_name="аватарка",
                    ),
                ),
                (
                    "coffee_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="сколько раз пользователь пытался сварить кофе",
                        verbose_name="количество переходов по /coffee/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        related_query_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "дополнительное поле пользователя",
                "verbose_name_plural": "дополнительные поля пользователей",
            },
        ),
    ]
