# Generated by Django 4.2.9 on 2024-03-21 20:55

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_userproxy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProxy",
        ),
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", users.models.UserProxyManager()),
            ],
        ),
    ]
