# Generated by Django 4.2.9 on 2024-03-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_delete_userproxy_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="deactivation_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата деактивации аккаунта"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="login_attempts",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество попыток входа"
            ),
        ),
    ]
