# Generated by Django 4.2.9 on 2024-03-27 16:35

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_login_attempts_profile_attempts_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="укажите дату рождения",
                null=True,
                validators=[users.validators.birthday_validator],
                verbose_name="дата рождения",
            ),
        ),
    ]
