# Generated by Django 4.2.9 on 2024-03-25 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0012_alter_category_name_alter_item_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (1, "Ненависть"),
                            (2, "Неприязнь"),
                            (3, "Нейтрально"),
                            (4, "Обожание"),
                            (5, "Любовь"),
                        ]
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="товар которому поставили оценку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        related_query_name="grades",
                        to="catalog.category",
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="пользователь который поставил оценку",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        related_query_name="grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "оценка",
                "verbose_name_plural": "оценки",
            },
        ),
    ]
