# Generated by Django 4.2 on 2024-03-02 18:18

import core.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_item_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="находится на домашней странице",
                verbose_name="в главном",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
    ]
