# Generated by Django 4.2 on 2024-03-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_item_category_alter_itemsecondaryimage_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                help_text="выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="items",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="выберите теги",
                related_name="items",
                related_query_name="items",
                to="catalog.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
            ),
        ),
    ]
