# Generated by Django 4.2 on 2024-03-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_item_category_alter_item_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalize_name",
            field=models.CharField(
                editable=False,
                help_text="этот field не редактируется и нормализует field(name)",
                max_length=150,
                verbose_name="нормализованное название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="normalize_name",
            field=models.CharField(
                editable=False,
                help_text="этот field не редактируется и нормализует field(name)",
                max_length=150,
                verbose_name="нормализованное название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalize_name",
            field=models.CharField(
                editable=False,
                help_text="этот field не редактируется и нормализует field(name)",
                max_length=150,
                verbose_name="нормализованное название",
            ),
        ),
    ]
