# Generated by Django 4.2.9 on 2024-03-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_item_created_alter_item_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
    ]
