# Generated by Django 4.2.9 on 2024-03-13 17:38

import core.models
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_itemmainimage_item_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="напишите название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(
                help_text="напишите название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="itemmainimage",
            name="item",
            field=models.OneToOneField(
                help_text="товар изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                related_query_name="main_image",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                help_text="загрузите изображение",
                upload_to=core.models.get_path_image,
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="itemsecondaryimage",
            name="item",
            field=models.ForeignKey(
                help_text="товар изображения",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                related_query_name="images",
                to="catalog.item",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="напишите название",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
    ]
